#!/bin/sh

set -e
ANSI_RED='\033[0;31m'
ANSI_GREEN='\033[0;32m'
ANSI_YELLOW='\033[1;33m'
ANSI_RESET='\033[0m'

PATH_PROJECT=/var/www/ajur-media-maker
PATH_CONFIG=/etc/ajur/ajur-media-maker

FLAG_CONFIG="0"

PHP_VERSIONS=$(ps -e -o stat,command | grep -E '^Ss\s+php-fpm' | grep -E '[0-9]+\.[0-9]+' -o)

case "$1" in
    configure)
        echo "\n ${ANSI_YELLOW} Running AJUR-MEDIA-MAKER post-install... ${ANSI_RESET} \n"

        mkdir -p ${PATH_PROJECT}/cache
        mkdir -p ${PATH_PROJECT}/files.download
        mkdir -p ${PATH_PROJECT}/files.upload
        mkdir -p ${PATH_PROJECT}/logs

        echo -n "Checking symlink from '${PATH_PROJECT}/public/storage' to '/storage' directory"
        if [ ! -L "${PATH_PROJECT}/public/storage" ] ; then
            ln -s ${PATH_PROJECT}/files.download ${PATH_PROJECT}/public/storage ;
            echo "${ANSI_YELLOW} Created. ${ANSI_RESET}"
        else
            echo "${ANSI_GREEN} Present. ${ANSI_RESET}"
        fi
        echo

        echo -n "Checking _CREDENTIALS.CONF ..."
        if [ -e "${PATH_CONFIG}/_credentials.conf" ]; then
            echo "${ANSI_GREEN} FOUND ${ANSI_RESET}";
            FLAG_CONFIG="+";
        else
            echo "${ANSI_RED} NOT FOUND! ${ANSI_RESET}" ;
        fi

        echo

        echo " Clearing SMARTY cache"
        rm -f ${PATH_PROJECT}/cache/*
        echo "  Ok"

        echo "Fixing access rights..."
        chown -R www-data:www-data ${PATH_PROJECT}/*
        echo "${ANSI_GREEN} Ok. ${ANSI_RESET}"

        echo
        echo "Restarting all running php-fpm processes..."
        for version in $PHP_VERSIONS; do echo "Restarting ${ANSI_YELLOW}php${version}-fpm${ANSI_RESET} process..."; systemctl restart php${version}-fpm; done
        echo "${ANSI_GREEN}Finished.${ANSI_RESET}"

        echo
        echo "${ANSI_YELLOW} ... post-install finished. ${ANSI_RESET}"
        echo

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
